# 🚀 NumPy & Pandas  — Ваш путь к мастерству анализа данных!

### 📊 Что включает этот ноутбук?
- 5 недель интенсивного обучения
- 100 практических заданий EASY уровня
- 50 задач MEDIUM сложности
- 25 вызовов HARD уровня
- 25 концептуальных вопросов для глубокого понимания
- 3 финальных проекта для закрепления навыков

### 🧠 Чему вы научитесь?
После завершения этого курса вы будете уверенно:
- Манипулировать многомерными массивами данных с NumPy
- Эффективно обрабатывать и анализировать таблицы с Pandas
- Очищать и трансформировать данные для анализа
- Выполнять сложные агрегации и группировки
- Оптимизировать код для работы с большими объемами данных
- Подготавливать данные для машинного обучения

### 💪 Какие навыки вы приобретете?
- **NumPy**: векторизация, индексация, математические операции, работа с массивами
- **Pandas**: обработка данных, фильтрация, группировка, объединение таблиц
- **Предобработка данных**: очистка, трансформация, нормализация
- **Готовность к ML**: подготовка признаков, работа с категориальными данными

### 🔮 Что дальше?
После завершения этого курса вы будете полностью готовы к следующему этапу — **Машинному обучению**! Вы сможете применять алгоритмы ML к уже подготовленным данным и создавать модели, решающие реальные задачи.

### 🎯 Ваша цель
Стать мастером NumPy и Pandas до начала ML-этапа

**Начнем наше путешествие в мир данных!** 🚀

# 🧭 НЕДЕЛЯ 1 — Основы NumPy и Pandas

### 🎯 Цель недели: Понимание основных операций с массивами и таблицами.

### 📚 Введение в методы недели

В этой секции мы кратко рассмотрим основные методы NumPy и Pandas, которые будут использоваться в заданиях этой недели. Цель — освежить память и убедиться, что вы знакомы с базовыми операциями.

## Установка окружения и импорт
```python
# Рекомендуется использовать venv / conda. Установите пакеты:
# pip install numpy pandas matplotlib jupyterlab
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('numpy', np.__version__)
print('pandas', pd.__version__)
```
#### NumPy:
*   `np.array()`: Создание массива из списка или кортежа.
*   `np.zeros()`, `np.ones()`: Создание массивов, заполненных нулями или единицами.
*   `np.arange()`: Создание массива с последовательными значениями.
*   `np.random.randint()`: Генерация случайных целых чисел.
*   `reshape()`: Изменение формы массива.
*   `max()`, `min()`, `mean()`: Вычисление максимального, минимального и среднего значений.
*   `.T`: Транспонирование массива (обмен строк и столбцов).
*   Арифметические операции (+, -, *, /): Поэлементные операции над массивами.
*   Индексация и срезы: Доступ к элементам или подмассивам.
*   Булева индексация: Выбор элементов по условию.
*   `.to_numpy()`: Преобразование DataFrame в массив NumPy.

#### Pandas:
*   `pd.DataFrame()`: Создание DataFrame из словаря, списка списков или других структур.
*   `pd.Series()`: Создание одномерной структуры данных Series.
*   `head()`: Просмотр первых строк DataFrame.
*   `info()`: Получение краткой сводки о DataFrame (типы данных, пропущенные значения).
*   `describe()`: Получение описательной статистики для числовых столбцов.
*   `df["колонка"]`: Выбор столбца по имени.
*   Булева индексация: Выбор строк по условию.
*   Добавление/удаление столбцов: Присваивание нового столбца или использование `drop()`.
*   `rename()`: Переименование столбцов.
*   `sum()`: Вычисление суммы элементов Series или столбца DataFrame.
*   `.str.upper()`: Применение строковых операций к элементам Series.
*   `fillna()`: Заполнение пропущенных значений.
*   `drop_duplicates()`: Удаление дублирующихся строк.
*   `pd.get_dummies()`: Преобразование категориальных данных в One-Hot Encoding.
*   `apply()`: Применение функции к Series или DataFrame.
*   `groupby()`: Группировка данных по одному или нескольким столбцам.
*   `np.linalg.det()`: Вычисление определителя матрицы (NumPy).

## 💡 EASY Задания

1. Создайте одномерный массив NumPy из 10 нулей, используя `np.zeros()`.

In [2]:
import numpy as np
import pandas as pd

arr_0_10 =np.zeros(10)
print('Array with ten "0" values :')
print(arr_0_10)

Array with ten "0" values :
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Создайте одномерный массив NumPy из 10 единиц, используя `np.ones()`.

In [2]:
array_1_10 = np.ones(10)
print('Array with ten "1" values :')
print(array_1_10)

Array with ten "1" values :
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3. Создайте одномерный массив NumPy из 10 случайных целых чисел в диапазоне от 1 до 100, используя `np.random.randint()`.

In [4]:
array_randoms_10 = np.random.randint(10,size=(10))
print('Array with ten "Random" values in 0-10 range:')
print(array_randoms_10)

Array with ten "Random" values :
[8 7 8 2 9 3 0 5 2 8]


4. Создайте массив NumPy 3x3 со значениями от 0 до 8, используя `np.arange()` и `reshape()`.

In [7]:
array_3_3 = np.arange(9).reshape(3,3)
print('Array with 3x3 size  :')
print(array_3_3)

Array with 3x3 size  :
[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Измените форму массива из предыдущего задания на 1x9, используя `reshape()`.

Подсказка: используйте результат предыдущего задания и примените к нему метод reshape.

In [9]:
array_1_9 = array_3_3.reshape(9)
print('Array with 1x9 size : ')
print(array_1_9)

Array with 1x9 size : 
[0 1 2 3 4 5 6 7 8]


6. Создайте массив NumPy 5x5 со случайными значениями и найдите максимальное, минимальное и среднее значение, используя `max()`, `min()`, `mean()`.

In [11]:
arr5_5 = np.random.randint(10,90,size=(5,5))

max_num = arr5_5.max()
min_num = arr5_5.min()
mean_num = arr5_5.mean()
print('Array with 5x5 size  :')
print(arr5_5)
print(f'Max number : {max_num} , Min number : {min_num} , Mean number : {mean_num}')

Array with 5x5 size  :
[[40 55 13 60 40]
 [31 55 66 49 18]
 [39 24 52 51 52]
 [11 53 88 71 81]
 [34 80 20 31 60]]
Max number : 88 , Min number : 11 , Mean number : 46.96


7. Создайте массив NumPy со значениями от 1 до 10 и извлеките все четные числа, используя булеву индексацию.

In [18]:
arr = np.arange(1,10)
print(f'Array : {arr}')
print(f'Odd numbers : {}')
# print(f'Even numbers :')

Array : [1 2 3 4 5 6 7 8 9]
Odd numbers : [2 1 2 1 2 1 2 1 2]


8. Создайте массив NumPy 2x3 и транспонируйте его, используя `.T`.

In [20]:
arr2_3 = np.arange(10,16).reshape(2,3)
print(f'Array : {arr2_3}')
print(f'Transformed Array : {arr2_3.T}')

Array : [[10 11 12]
 [13 14 15]]
Transformed Array : [[10 13]
 [11 14]
 [12 15]]


9. Создайте два массива NumPy одинаковой формы и выполните поэлементное сложение, вычитание, умножение и деление.

In [5]:
arr_1 = np.arange(12).reshape(3,4)
arr_2 = np.arange(12 , 24).reshape(3,4)

addintion = arr_1+arr_2
subtraction = arr_1-arr_2
multiplication = arr_1*arr_2
division = arr_1/arr_2

print(f'Addition : {addintion}')
print(f'Subtraction : {subtraction}')
print(f'Multiplication : {multiplication}')
print(f'Division : {division}')

Addition : [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Subtraction : [[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
Multiplication : [[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
Division : [[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


10. Создайте DataFrame Pandas из словаря с данными о студентах (имя, возраст, оценка), используя `pd.DataFrame()`.

In [19]:
student_dictionary = [
    {'Name': 'Bob',
     'Age': 12,
     'Grade': 4, },
{'Name': 'Alex',
 'Age': 25,
 'Grade': 3} ,
    {'Name': 'John',
     'Age': 12,
     'Grade': 5} ,
    {'Name': 'Doe',
     'Age': 22,
     'Grade': 0},
    {'Name': 'Jerry',
     'Age': 12,
     'Grade': 5}
]


student_df = pd.DataFrame(student_dictionary)
print(stdudent_df)

    Name  Age  Grade
0    Bob   12      4
1   Alex   12      3
2   John   12      5
3    Doe   12      0
4  Jerry   12      5


🔥 Отлично! Вы уже освоили базовые операции с NumPy и Pandas. Продолжайте в том же духе!

11. Выведите первые 3 строки созданного DataFrame, используя `head()`.

In [10]:
print('First 3 rows of Student DataFrame:' , student_df.head(3))

First 3 rows of Student DataFrame:    Name  Age  Grade
0   Bob   12      4
1  Alex   12      3
2  John   12      5


12. Выведите информацию о DataFrame (типы данных, количество непустых значений), используя `info()`.

In [12]:
print('DataFrame informations : ' , student_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Grade   5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
DataFrame informations :  None


13. Выведите описательную статистику для числовых столбцов DataFrame, используя `describe()`.

In [14]:
print("Statistics of DataFrame's Numeric colums\n" , student_df.describe())

Statistics of DataFrame's Numeric colums
         Age     Grade
count   5.0  5.000000
mean   12.0  3.400000
std     0.0  2.073644
min    12.0  0.000000
25%    12.0  3.000000
50%    12.0  4.000000
75%    12.0  5.000000
max    12.0  5.000000


14. Выберите столбец 'имя' из DataFrame, используя синтаксис `df['колонка']`.

In [18]:
print(f"DataFrame colums via index-calling: ,\n Student's Age :\n{student_df['Age']} ,\n Student's Grade: \n{student_df["Grade"]} ,\nStudent's Name: \n{student_df['Name']}")

DataFrame colums via index-calling: ,
 Student's Age :
0    12
1    12
2    12
3    12
4    12
Name: Age, dtype: int64 ,
 Student's Grade: 
0    4
1    3
2    5
3    0
4    5
Name: Grade, dtype: int64 ,
Student's Name: 
0      Bob
1     Alex
2     John
3      Doe
4    Jerry
Name: Name, dtype: object


15. Выберите строки DataFrame, где 'возраст' больше 20, используя булеву индексацию.

In [21]:
print("Students who's grater than 20:\n" , student_df[student_df['Age'] > 20])

Students who's grater than 20:
    Name  Age  Grade
1  Alex   25      3
3   Doe   22      0


16. Добавьте новый столбец 'город' в DataFrame.

In [23]:
Country = ['Tashkent' , 'Samarkand' , 'Namangan' ,'Khiva' , 'Tashkent']
student_df['Country'] = pd.DataFrame(Country , columns =['Country'])
print(f"New Student's DtaFrame , which has a student's countries data \n" , student_df)

New Student's DtaFrame , which has a student's countries data 
     Name  Age  Grade    Counrty
0    Bob   12      4   Tashkent
1   Alex   25      3  Samarkand
2   John   12      5   Namangan
3    Doe   22      0      Khiva
4  Jerry   12      5   Tashkent


17. Удалите столбец 'город' из DataFrame, используя `drop()`.

In [25]:
print("Student's countries data column deleted \n" , student_df.drop('Country', axis = 1))

Student's countries data column deleted 
     Name  Age  Grade
0    Bob   12      4
1   Alex   25      3
2   John   12      5
3    Doe   22      0
4  Jerry   12      5


18. Переименуйте столбец 'оценка' в 'балл' в DataFrame, используя `rename()`.

In [26]:
print("Student's Grade column renamed to Scores \n" , student_df.rename({'Grade':'Scores'}))

Student's Grade column renamed to Scores 
     Name  Age  Grade    Counrty
0    Bob   12      4   Tashkent
1   Alex   25      3  Samarkand
2   John   12      5   Namangan
3    Doe   22      0      Khiva
4  Jerry   12      5   Tashkent


19. Создайте Series Pandas из списка чисел и найдите его сумму, используя `sum()`.

In [33]:
array = np.arange(1,100)
numbers_series = pd.Series(array)
print("Series numbers summ :" , numbers_series.sum())

Series numbers summ : 4950


20. Создайте Series Pandas из списка строк и преобразуйте его в верхний регистр, используя `.str.upper()`.

In [44]:
fruits = [
    'apple'  , 'banana' , 'orange' ,'limon' , 'strawberry' , 'pear' , 'apple' ]
fruits_series = pd.Series(fruits)
print(f"Fruits name's  latters changed to Upper :\n "  , fruits_series.str.upper())


Fruits name's  latters changed to Upper :
  0         APPLE
1        BANANA
2        ORANGE
3         LIMON
4    STRAWBERRY
5          PEAR
6         APPLE
dtype: object


🎯 Поздравляем! Вы успешно завершили все EASY задания первой недели. Вы уже можете создавать и манипулировать данными в NumPy и Pandas!

## ⚙️ MEDIUM Задания

1. Создайте DataFrame из массива NumPy 4x4 случайных чисел. Затем сгруппируйте данные по первому столбцу (если он категориальный) и вычислите среднее значение второго столбца, а результат агрегации преобразуйте обратно в массив NumPy.

DataFrame:
    A         B         C         D
0  1  0.984914  0.974341  0.015428
1  2  0.475093  0.873498  0.883445
2  1  0.054755  0.388051  0.861997
3  2  0.488672  0.604740  0.033448

Средние значения (Series):
 A
1    0.519835
2    0.481882
Name: B, dtype: float64

Итоговый массив NumPy: [0.51983467 0.48188224]


2. Создайте массив NumPy 4x4 со случайными числами. Замените все значения в центральном квадрате 2x2 на 0, используя срезы и присваивание.

Подсказка: для доступа к центральному квадрату 2x2 в массиве 4x4 используйте срезы arr[1:3, 1:3]

array([[0.14156053, 0.03215145, 0.39444659, 0.56738487],
       [0.75385642, 0.        , 0.        , 0.58102797],
       [0.2316206 , 0.        , 0.        , 0.46290348],
       [0.94952522, 0.45506654, 0.84950532, 0.77446229]])

3. Создайте массив NumPy 5x5. Нормализуйте все значения в массиве так, чтобы они находились в диапазоне от 0 до 1, используя формулу `(x - min) / (max - min)` и `min()`, `max()`.

array([280.4, 296.4, 312.4, 328.4, 344.4])

4. Создайте два одномерных массива NumPy `a` и `b`. Объедините их в один двумерный массив, используя `np.vstack()` и `np.hstack()`.

In [ ]:
# 🧩 Ваш код здесь

5. Создайте DataFrame Pandas с данными о продажах (товар, количество, цена). Вычислите общую стоимость для каждой строки (количество * цена), используя поэлементное умножение столбцов.

In [ ]:
# 🧩 Ваш код здесь

💪 Вы отлично справляетесь с более сложными задачами! Продолжайте в том же духе!

6. Загрузите CSV-файл с данными о погоде (дата, температура, влажность). Отфильтруйте строки, где температура выше среднего значения по всему столбцу, используя `mean()`.

Подсказка: если у вас нет файла, создайте тестовый DataFrame с соответствующими столбцами.

In [ ]:
# 🧩 Ваш код здесь

7. Создайте DataFrame с пропущенными значениями (NaN). Заполните все пропущенные значения в числовом столбце его средним значением, используя `fillna()` и `mean()`.

In [ ]:
# 🧩 Ваш код здесь

8. Создайте DataFrame с дублирующимися строками. Удалите дубликаты, сохраняя только первое вхождение, используя `drop_duplicates()`.

In [ ]:
# 🧩 Ваш код здесь

9. Создайте DataFrame с категориальным столбцом. Преобразуйте его в числовой формат с помощью One-Hot Encoding, используя `pd.get_dummies()`.

In [ ]:
# 🧩 Ваш код здесь

10. Создайте DataFrame с числовым столбцом. Примените функцию, которая возводит каждое число в квадрат, используя `apply()` и лямбда-функцию.

In [ ]:
# 🧩 Ваш код здесь

🏆 Отлично! Вы успешно справились со всеми заданиями среднего уровня сложности. Теперь вы готовы к настоящим вызовам!

## 🔥 HARD Задания

1. Используя NumPy, реализуйте функцию для вычисления ковариационной матрицы двух массивов без использования `np.cov()`. Сравните результат с `np.cov()`.

2. Создайте DataFrame Pandas с данными о транзакциях (ID пользователя, сумма, дата). Найдите топ-5 пользователей по общей сумме транзакций за последний месяц, используя фильтрацию по дате, `groupby()`, `sum()`, `nlargest()`.

In [ ]:
# 🧩 Ваш код здесь

3. Используя NumPy, реализуйте алгоритм K-Means для кластеризации случайных 2D точек без использования библиотек машинного обучения (только базовые операции NumPy).

In [ ]:
# 🧩 Ваш код здесь

4. Загрузите большой CSV-файл (например, 100 000 строк). Эффективно вычислите скользящее среднее для числового столбца с окном в 10 элементов, используя `rolling().mean()`.

Подсказка: если у вас нет большого файла, создайте тестовый DataFrame с достаточным количеством строк.

In [ ]:
# 🧩 Ваш код здесь

5. Создайте DataFrame с иерархическим индексом (MultiIndex) для данных о продажах по регионам и продуктам. Выберите данные для конкретного региона и всех продуктов, используя `loc[]`.

In [ ]:
# 🧩 Ваш код здесь

🔥 Впечатляюще! Вы справились с самыми сложными задачами первой недели. Это настоящее достижение!

## 🧠 CONCEPT Задания

1. Объясните разницу между `ndarray` и `DataFrame` в контексте хранения и обработки данных. Когда следует использовать каждый из них?

✍️ Ваш ответ здесь

2. Опишите концепцию векторизации в NumPy. Почему она важна для производительности и как она работает?

✍️ Ваш ответ здесь

3. Объясните, что такое широковещание (broadcasting) в NumPy. Приведите примеры его использования и правила.

✍️ Ваш ответ здесь

4. В чем разница между копией и представлением (view) массива в NumPy? Приведите примеры, когда создается копия, а когда представление.

✍️ Ваш ответ здесь

5. Опишите основные типы данных (dtypes) в NumPy и Pandas. Почему важно правильно выбирать тип данных для столбца или массива?

✍️ Ваш ответ здесь

6. Почему важно избегать явных циклов Python при работе с большими массивами NumPy и DataFrame Pandas?

✍️ Ваш ответ здесь

🏁 **Поздравляем! Неделя 1 завершена.**

💪 Вы продвинулись на 20% пути к профессиональному уровню.

🧠 Вы освоили основы NumPy и Pandas, научились создавать и манипулировать данными, а также поняли ключевые концепции этих библиотек. Это отличный фундамент для дальнейшего обучения!

# 🧭 НЕДЕЛЯ 2 — Индексация, агрегация, объединение

### 🎯 Цель недели: Индексация, агрегация, объединение.

### 📚 Введение в методы недели

В этой секции мы кратко рассмотрим основные методы NumPy и Pandas, которые будут использоваться в заданиях этой недели. Цель — освежить память и убедиться, что вы знакомы с базовыми операциями.

#### NumPy:
*   Индексация (прямая, срезы): Доступ к элементам и подмассивам.
*   `reshape()`, `flatten()`: Изменение формы массива.
*   `sum(axis)`: Суммирование элементов по осям.
*   `astype()`: Изменение типа данных массива.
*   `np.sqrt()`: Поэлементное вычисление квадратного корня.
*   `max(axis)`: Нахождение максимального значения по осям.
*   `np.where()`: Условное изменение значений в массиве.
*   `np.unique()`: Нахождение уникальных значений.
*   `argsort()`: Возвращает индексы, которые отсортировали бы массив.

#### Pandas:
*   `loc[]`, `iloc[]`: Индексация по меткам и по позициям.
*   `sum()`, `value_counts()`: Агрегирующие функции.
*   `pd.merge()`: Объединение DataFrame по общему столбцу.
*   `.dt.year`: Извлечение года из столбца дат.
*   Арифметические операции между столбцами.
*   `sort_values()`: Сортировка DataFrame по значениям столбца.
*   `reset_index()`: Сброс индекса DataFrame.
*   `groupby()`: Группировка данных.
*   `fillna()`: Заполнение пропущенных значений.
*   `pd.concat()`: Объединение DataFrame по осям.
*   `pd.qcut()`: Разделение данных на квантили.
*   `pct_change()`: Вычисление процентного изменения.
*   `rolling().mean()`: Скользящее среднее.
*   `agg()`: Применение нескольких агрегирующих функций.
*   `pivot_table()`: Создание сводных таблиц.
*   `filter()`: Фильтрация групп после `groupby()`.
*   `size()`: Размер группы в `groupby()`.

## 💡 EASY Задания

1. Создайте массив NumPy 4x4 со случайными целыми числами от 1 до 10. Извлеките элемент во второй строке, третьем столбце, используя прямую индексацию.

In [ ]:
# 🧩 Ваш код здесь

2. Создайте DataFrame Pandas из 5 строк и 3 столбцов с произвольными данными. Выберите столбец по его имени.

In [ ]:
# 🧩 Ваш код здесь

3. Создайте массив NumPy 3x3. Извлеките первую строку и последний столбец, используя срезы.

In [ ]:
# 🧩 Ваш код здесь

4. Создайте DataFrame Pandas. Выберите строки с индексами 0, 2, 4, используя `loc[]`.

In [ ]:
# 🧩 Ваш код здесь

5. Создайте массив NumPy 5x5. Извлеките подмассив, состоящий из центральных 3x3 элементов.

In [ ]:
# 🧩 Ваш код здесь

6. Создайте DataFrame Pandas. Выберите строки с индексами 1, 3 и столбцы с индексами 0, 2, используя `iloc[]`.

In [ ]:
# 🧩 Ваш код здесь

7. Создайте массив NumPy 1D из 10 элементов. Измените его форму на 2D (2x5), затем обратно на 1D, используя `reshape()` и `flatten()`.

In [ ]:
# 🧩 Ваш код здесь

8. Создайте DataFrame Pandas с числовым столбцом. Найдите сумму всех значений в этом столбце, используя `sum()`.

In [ ]:
# 🧩 Ваш код здесь

9. Создайте массив NumPy 3x3. Найдите сумму элементов по каждой строке и по каждому столбцу, используя `sum()` с параметром `axis`.

In [ ]:
# 🧩 Ваш код здесь

10. Создайте DataFrame Pandas с категориальным столбцом. Подсчитайте количество уникальных значений в этом столбце, используя `value_counts()`.

In [ ]:
# 🧩 Ваш код здесь

🔥 Отлично! Вы уже освоили половину EASY заданий второй недели. Продолжайте в том же духе!

11. Создайте два DataFrame Pandas с общим столбцом. Объедините их по этому столбцу, используя `pd.merge()` с типом `inner`.

In [ ]:
# 🧩 Ваш код здесь

12. Создайте массив NumPy 1D. Измените его тип данных на `float64`, используя `astype()`.

In [ ]:
# 🧩 Ваш код здесь

13. Создайте DataFrame Pandas с датами. Извлеките год из столбца дат, используя аксессор `.dt.year`.

In [ ]:
# 🧩 Ваш код здесь

14. Создайте массив NumPy. Примените к нему универсальную функцию `np.sqrt()`.

In [ ]:
# 🧩 Ваш код здесь

15. Создайте DataFrame Pandas. Добавьте новый столбец, который является результатом деления двух существующих числовых столбцов.

In [ ]:
# 🧩 Ваш код здесь

16. Создайте массив NumPy 2D. Найдите максимальное значение в каждой строке, используя `max()` с параметром `axis`.

In [ ]:
# 🧩 Ваш код здесь

17. Создайте DataFrame Pandas. Отсортируйте его по значениям одного из столбцов в порядке убывания, используя `sort_values()`.

In [ ]:
# 🧩 Ваш код здесь

18. Создайте массив NumPy 1D. Используйте `np.where()` для замены всех значений больше 5 на 10.

In [ ]:
# 🧩 Ваш код здесь

19. Создайте DataFrame Pandas. Сбросьте его индекс и сделайте старый индекс новым столбцом, используя `reset_index()`.

In [ ]:
# 🧩 Ваш код здесь

20. Создайте массив NumPy из случайных чисел. Найдите все уникальные значения в массиве, используя `np.unique()`.

In [ ]:
# 🧩 Ваш код здесь

🎯 Поздравляем! Вы успешно завершили все EASY задания второй недели. Вы уже можете эффективно индексировать и агрегировать данные!

## ⚙️ MEDIUM Задания

1. Загрузите CSV-файл с данными о продажах (дата, регион, товар, сумма). Сгруппируйте данные по 'региону' и 'товару' и вычислите общую сумму продаж для каждой группы, используя `groupby()` и `sum()`.

Подсказка: если у вас нет файла, создайте тестовый DataFrame с соответствующими столбцами.

In [ ]:
# 🧩 Ваш код здесь

2. Создайте массив NumPy 2D. Отфильтруйте строки, где сумма элементов строки превышает заданный порог, используя `np.sum()` и булеву индексацию.

In [ ]:
# 🧩 Ваш код здесь

3. Создайте два DataFrame Pandas: один с информацией о сотрудниках (ID, Имя, Отдел), другой с информацией о зарплатах (ID, Зарплата, Дата). Объедините их, чтобы получить полную информацию о зарплатах сотрудников, используя `pd.merge()` с типом `left`.

In [ ]:
# 🧩 Ваш код здесь

4. Создайте DataFrame Pandas с пропущенными значениями. Заполните пропущенные значения в каждом столбце методом `ffill()` (forward fill).

In [ ]:
# 🧩 Ваш код здесь

5. Используя NumPy, создайте матрицу 5x5. Вычислите среднее значение каждого столбца, исключая максимальное и минимальное значения в этом столбце.

In [ ]:
# 🧩 Ваш код здесь

💪 Вы отлично справляетесь с более сложными задачами! Продолжайте в том же духе!

6. Создайте DataFrame Pandas с данными о заказах (ID заказа, ID клиента, Сумма). Найдите ID клиентов, которые сделали более 3 заказов, и общую сумму их заказов, используя `groupby()`, `size()`, `filter()`.

In [ ]:
# 🧩 Ваш код здесь

7. Создайте массив NumPy 2D. Отсортируйте его по значениям второго столбца, используя `argsort()`.

In [ ]:
# 🧩 Ваш код здесь

8. Создайте DataFrame Pandas с числовым столбцом. Разбейте этот столбец на 4 равных интервала (квантили) и присвойте каждой строке метку интервала, используя `pd.qcut()`.

In [ ]:
# 🧩 Ваш код здесь

9. Создайте два DataFrame Pandas. Объедините их вертикально, добавив один под другой, используя `pd.concat()`.

In [ ]:
# 🧩 Ваш код здесь

10. Используя NumPy, реализуйте функцию для вычисления евклидова расстояния между двумя векторами.

In [ ]:
# 🧩 Ваш код здесь

🏆 Отлично! Вы успешно справились со всеми заданиями среднего уровня сложности. Теперь вы готовы к настоящим вызовам!

## 🔥 HARD Задания

1. Загрузите данные о ценах акций (дата, цена открытия, цена закрытия). Вычислите ежедневную доходность акций, а затем скользящую среднюю доходность за 7 дней, используя `pct_change()` и `rolling().mean()`.

In [ ]:
# 🧩 Ваш код здесь

2. Используя NumPy, создайте функцию, которая принимает 2D массив и возвращает массив, где каждая строка нормализована по L2-норме (евклидова норма).

In [ ]:
# 🧩 Ваш код здесь

3. Создайте DataFrame Pandas с данными о транзакциях (ID клиента, дата, сумма). Найдите для каждого клиента его первую и последнюю транзакцию, а также среднюю сумму транзакции, используя `groupby()` и агрегацию с `agg()`.

In [ ]:
# 🧩 Ваш код здесь

4. Используя NumPy, реализуйте функцию для нахождения k-ближайших соседей для заданной точки в 2D пространстве (без использования готовых библиотек ML).

In [ ]:
# 🧩 Ваш код здесь

5. Создайте DataFrame Pandas с несколькими категориальными столбцами. Создайте сводную таблицу (pivot table), которая показывает среднее значение числового столбца для каждой комбинации категорий, используя `pivot_table()`.

In [ ]:
# 🧩 Ваш код здесь

🔥 Впечатляюще! Вы справились с самыми сложными задачами второй недели. Это настоящее достижение!

## 🧠 CONCEPT Задания

1. Объясните разницу между `loc[]` и `iloc[]` в Pandas. Приведите примеры, когда каждый из них предпочтителен.

✍️ Ваш ответ здесь

2. Что такое агрегация данных в Pandas? Приведите примеры часто используемых агрегирующих функций и их применение.

✍️ Ваш ответ здесь

3. Опишите концепцию объединения (merge, join, concatenate) в Pandas. В чем их различия и когда какой метод использовать?

✍️ Ваш ответ здесь

4. Объясните, что такое MultiIndex (иерархический индекс) в Pandas. Приведите примеры его создания и использования для индексации данных.

✍️ Ваш ответ здесь

5. В чем преимущества и недостатки использования `apply()` по сравнению с векторизованными операциями в Pandas?

✍️ Ваш ответ здесь

6. Сравните производительность вычисления суммы элементов большого массива NumPy с использованием цикла Python и `np.sum()`. Объясните разницу.

✍️ Ваш ответ здесь

🏁 **Поздравляем! Неделя 2 завершена.**

💪 Вы продвинулись на 40% пути к профессиональному уровню.

🧠 Вы освоили индексацию, агрегацию и объединение данных в NumPy и Pandas. Эти навыки позволят вам эффективно работать с реальными наборами данных!

# 🧭 НЕДЕЛЯ 3 — Обработка данных, очистка, статистика

### 🎯 Цель недели: Обработка данных, очистка, статистика.

### 📚 Введение в методы недели

В этой секции мы кратко рассмотрим основные методы NumPy и Pandas, которые будут использоваться в заданиях этой недели. Цель — освежить память и убедиться, что вы знакомы с базовыми операциями.

#### NumPy:
*   `isnull()`, `np.nan`: Проверка и представление пропущенных значений.
*   `np.mean()`, `np.median()`, `np.std()`: Статистические функции.
*   `np.sum(axis)`: Суммирование элементов по осям.
*   `np.power()`: Возведение в степень.
*   `np.clip()`: Ограничение значений массива.
*   Булева индексация: Удаление элементов.

#### Pandas:
*   `isnull()`, `sum()`: Проверка и подсчет пропущенных значений.
*   `fillna()`: Заполнение пропущенных значений (с различными стратегиями).
*   `drop_duplicates()`: Удаление дубликатов.
*   `astype()`: Изменение типа данных.
*   `mean()`, `median()`, `std()`, `mode()`: Статистические функции для Series/DataFrame.
*   `cumsum()`: Кумулятивная сумма.
*   `pd.to_datetime()`, `.dt.year`, `.dt.month`, `.dt.day`: Работа с датами и временем.
*   `.str.lower()`, `.str.contains()`, `.str.extract()`: Строковые операции.
*   `nunique()`: Количество уникальных значений.
*   `round()`: Округление значений.
*   `pct_change()`: Процентное изменение.
*   `pd.cut()`: Разделение данных на интервалы.
*   `corr()`: Вычисление корреляционной матрицы.
*   `groupby()`, `agg()`: Группировка и агрегация данных.
*   `idxmax()`: Индекс максимального значения.

## 💡 EASY Задания

1. Создайте DataFrame Pandas с 5 строками и 3 столбцами, содержащий несколько пропущенных значений (NaN). Проверьте наличие пропущенных значений, используя `isnull()` и `sum()`.

In [ ]:
# 🧩 Ваш код здесь

2. Создайте массив NumPy 1D с 10 элементами, включая несколько `np.nan`. Удалите все `np.nan` из массива, используя булеву индексацию.

In [ ]:
# 🧩 Ваш код здесь

3. Создайте DataFrame Pandas. Заполните все пропущенные значения в числовом столбце нулем, используя `fillna(0)`.

In [ ]:
# 🧩 Ваш код здесь

4. Создайте DataFrame с двумя одинаковыми строками. Удалите дубликаты, используя `drop_duplicates()`.

In [ ]:
# 🧩 Ваш код здесь

5. Создайте Series Pandas с числовыми данными, представленными как строки (например, '10', '20', '30'). Преобразуйте его в числовой тип данных, используя `astype(int)`.

In [ ]:
# 🧩 Ваш код здесь

6. Создайте массив NumPy 1D из 10 случайных чисел. Найдите его среднее значение, медиану и стандартное отклонение, используя `np.mean()`, `np.median()`, `np.std()`.

In [ ]:
# 🧩 Ваш код здесь

7. Создайте DataFrame Pandas с данными о возрасте. Найдите средний возраст, используя `mean()`.

In [ ]:
# 🧩 Ваш код здесь

8. Создайте DataFrame с категориальным столбцом. Найдите моду (наиболее часто встречающееся значение) в этом столбце, используя `mode()`.

In [ ]:
# 🧩 Ваш код здесь

9. Создайте DataFrame с числовым столбцом. Вычислите кумулятивную сумму этого столбца, используя `cumsum()`.

In [ ]:
# 🧩 Ваш код здесь

10. Создайте массив NumPy 2D. Вычислите сумму элементов по каждой строке, используя `np.sum(axis=1)`.

In [ ]:
# 🧩 Ваш код здесь

🔥 Отлично! Вы уже освоили половину EASY заданий третьей недели. Продолжайте в том же духе!

11. Создайте DataFrame Pandas с датами. Отфильтруйте строки, где дата находится до определенного года, используя `pd.to_datetime()` и булеву индексацию.

In [ ]:
# 🧩 Ваш код здесь

12. Создайте Series Pandas с текстовыми данными. Преобразуйте все строки в нижний регистр, используя `.str.lower()`.

In [ ]:
# 🧩 Ваш код здесь

13. Создайте массив NumPy 1D. Примените к каждому элементу функцию, которая возводит его в куб, используя `np.power()` или `**`.

In [ ]:
# 🧩 Ваш код здесь

14. Создайте DataFrame Pandas. Вычислите количество уникальных значений в каждом столбце, используя `nunique()`.

In [ ]:
# 🧩 Ваш код здесь

15. Создайте DataFrame с числовым столбцом. Округлите все значения до двух десятичных знаков, используя `round()`.

In [ ]:
# 🧩 Ваш код здесь

16. Создайте массив NumPy 2D. Замените все значения, превышающие 10, на 10, используя `np.clip()`.

In [ ]:
# 🧩 Ваш код здесь

17. Создайте DataFrame Pandas. Добавьте новый столбец, который является индикатором (True/False) для строк, где значение в другом столбце больше заданного порога.

In [ ]:
# 🧩 Ваш код здесь

18. Создайте Series Pandas. Проверьте, содержит ли каждая строка определенную подстроку, используя `.str.contains()`.

In [ ]:
# 🧩 Ваш код здесь

19. Создайте массив NumPy 1D. Отсортируйте его в порядке убывания, используя `np.sort()` и срезы.

In [ ]:
# 🧩 Ваш код здесь

20. Создайте DataFrame Pandas. Вычислите процент пропущенных значений для каждого столбца.

In [ ]:
# 🧩 Ваш код здесь

🎯 Поздравляем! Вы успешно завершили все EASY задания третьей недели. Вы уже можете эффективно обрабатывать и очищать данные!

## ⚙️ MEDIUM Задания

1. Загрузите CSV-файл с данными о продажах, содержащий пропущенные значения. Заполните пропущенные значения в столбце 'Цена' медианой этого столбца, а в столбце 'Категория' — наиболее частым значением (модой), используя `fillna()` и `median()`, `mode()`.

Подсказка: если у вас нет файла, создайте тестовый DataFrame с соответствующими столбцами.

In [ ]:
# 🧩 Ваш код здесь

2. Создайте DataFrame с данными о клиентах (ID, Имя, Возраст, Город). Найдите клиентов, у которых есть дубликаты по комбинации 'Имя' и 'Город', но не по 'ID', используя `duplicated()` с подмножеством столбцов.

In [ ]:
# 🧩 Ваш код здесь

3. Создайте массив NumPy 2D. Выполните стандартизацию данных (Z-score нормализацию) для каждого столбца: `(x - mean) / std`, используя `np.mean()` и `np.std()` с параметром `axis`.

In [ ]:
# 🧩 Ваш код здесь

4. Создайте DataFrame Pandas с данными о времени (например, время начала и окончания события). Вычислите продолжительность каждого события в минутах, используя разность дат и `dt.total_seconds()`.

In [ ]:
# 🧩 Ваш код здесь

5. Загрузите CSV-файл с данными о погоде (температура, осадки). Создайте новый столбец 'Температурная_категория' на основе значений температуры (например, 'Холодно', 'Нормально', 'Жарко'), используя `pd.cut()`.

In [ ]:
# 🧩 Ваш код здесь

💪 Вы отлично справляетесь с более сложными задачами! Продолжайте в том же духе!

6. Создайте DataFrame с данными о ценах акций. Вычислите ежедневное изменение цен в процентах и добавьте его как новый столбец, используя `pct_change()`.

In [ ]:
# 🧩 Ваш код здесь

7. Используя NumPy, реализуйте функцию для удаления выбросов (outliers) из одномерного массива, используя метод IQR (интерквартильный размах).

In [ ]:
# 🧩 Ваш код здесь

8. Создайте DataFrame Pandas с текстовым столбцом. Извлеките числовые значения из строк (например, 'Цена: 123.45 USD') и преобразуйте их в числовой тип, используя `.str.extract()` и `astype()`.

In [ ]:
# 🧩 Ваш код здесь

9. Создайте DataFrame с несколькими числовыми столбцами. Вычислите корреляционную матрицу между всеми числовыми столбцами, используя `corr()`.

In [ ]:
# 🧩 Ваш код здесь

10. Создайте DataFrame с данными о транзакциях. Разделите столбец 'Дата' на отдельные столбцы 'Год', 'Месяц', 'День', используя `dt.year`, `dt.month`, `dt.day`.

In [ ]:
# 🧩 Ваш код здесь

🏆 Отлично! Вы успешно справились со всеми заданиями среднего уровня сложности. Теперь вы готовы к настоящим вызовам!

## 🔥 HARD Задания

1. Загрузите большой CSV-файл с данными о сенсорах (timestamp, sensor_id, value). Определите, какие сенсоры имеют аномально большое количество пропущенных значений (например, более 20%), используя `groupby()`, `isnull().sum()`, и фильтрацию.

In [ ]:
# 🧩 Ваш код здесь

2. Используя NumPy, реализуйте функцию для сглаживания временного ряда с помощью экспоненциального скользящего среднего (Exponential Moving Average) без использования специализированных библиотек.

In [ ]:
# 🧩 Ваш код здесь

3. Создайте DataFrame Pandas с данными о клиентах (ID, Дата_регистрации, Дата_последней_активности). Вычислите 'возраст' клиента в днях и 'давность' последней активности в днях, используя `pd.to_datetime()` и разность дат.

In [ ]:
# 🧩 Ваш код здесь

4. Используя NumPy, создайте функцию для выполнения взвешенной линейной регрессии (Weighted Least Squares) для заданных данных `x`, `y` и весов `w`.

In [ ]:
# 🧩 Ваш код здесь

5. Создайте DataFrame с данными о продажах (Регион, Товар, Дата, Сумма). Для каждого региона и каждого товара найдите месяц с максимальной суммой продаж, используя `groupby()`, `dt.month`, `idxmax()`.

In [ ]:
# 🧩 Ваш код здесь

🔥 Впечатляюще! Вы справились с самыми сложными задачами третьей недели. Это настоящее достижение!

## 🧠 CONCEPT Задания

1. Объясните различные стратегии обработки пропущенных значений в Pandas (удаление, заполнение, интерполяция). Когда какую стратегию следует применять?

✍️ Ваш ответ здесь

2. Что такое Z-score нормализация и Min-Max масштабирование? В чем их различия и когда каждый метод предпочтителен?

✍️ Ваш ответ здесь

3. Опишите концепцию обработки текстовых данных в Pandas. Какие методы `.str` наиболее полезны и для каких задач?

✍️ Ваш ответ здесь

4. Объясните, что такое выбросы (outliers) в данных и почему их важно обнаруживать и обрабатывать. Какие методы для этого существуют в NumPy/Pandas?

✍️ Ваш ответ здесь

5. Опишите, как работать с временными рядами в Pandas. Какие типы данных и функции используются для анализа временных данных?

✍️ Ваш ответ здесь

6. Представьте, что вы работаете с очень большим датасетом, который не помещается в оперативную память. Какие стратегии и методы Pandas вы бы использовали для его обработки и анализа?

✍️ Ваш ответ здесь

🏁 **Поздравляем! Неделя 3 завершена.**

💪 Вы продвинулись на 60% пути к профессиональному уровню.

🧠 Вы освоили методы обработки, очистки данных и статистического анализа. Эти навыки критически важны для подготовки данных к машинному обучению!

# 🧭 НЕДЕЛЯ 4 — Мини-проекты, работа с реальными датасетами

### 🎯 Цель недели: Мини-проекты, работа с реальными датасетами.

### 📚 Введение в методы недели

В этой секции мы кратко рассмотрим основные методы NumPy и Pandas, которые будут использоваться в заданиях этой недели. Цель — освежить память и убедиться, что вы знакомы с базовыми операциями.

#### NumPy:
*   `np.save()`, `np.load()`: Сохранение и загрузка массивов.
*   `np.percentile()`: Вычисление перцентилей.
*   `np.eye()`: Создание единичной матрицы.
*   `np.random.normal()`: Генерация случайных чисел по нормальному распределению.
*   `np.linalg.svd()`: Сингулярное разложение.

#### Pandas:
*   `pd.read_csv()`, `to_csv()`: Чтение и запись CSV-файлов.
*   `head()`, `info()`, `.columns`: Обзор данных.
*   `value_counts()`, `nunique()`: Анализ уникальных значений.
*   `replace()`: Замена значений.
*   `groupby()`, `mean()`, `sum()`, `filter()`, `agg()`: Группировка и агрегация.
*   `pd.to_datetime()`, `.dt.month`: Работа с датами.
*   `fillna()`, `map()`: Обработка пропущенных значений и преобразование.
*   `merge()`: Объединение DataFrame.
*   `.str.extract()`: Извлечение строковых паттернов.
*   `interpolate()`: Интерполяция пропущенных значений.
*   `quantile()`, `std()`: Статистические функции для обнаружения аномалий.

## 💡 EASY Задания

1. Загрузите небольшой CSV-файл (например, с данными о продажах) в DataFrame Pandas, используя `pd.read_csv()`.

Подсказка: если у вас нет файла, создайте тестовый DataFrame и сохраните его в CSV.

In [ ]:
# 🧩 Ваш код здесь

2. Просмотрите первые 5 строк загруженного DataFrame, используя `head()`.

In [ ]:
# 🧩 Ваш код здесь

3. Выведите названия всех столбцов DataFrame, используя `.columns`.

In [ ]:
# 🧩 Ваш код здесь

4. Проверьте типы данных каждого столбца в DataFrame, используя `info()`.

In [ ]:
# 🧩 Ваш код здесь

5. Подсчитайте количество уникальных значений в одном из категориальных столбцов DataFrame, используя `value_counts()`.

In [ ]:
# 🧩 Ваш код здесь

6. Создайте новый столбец в DataFrame, который является результатом простой арифметической операции между двумя существующими числовыми столбцами.

In [ ]:
# 🧩 Ваш код здесь

7. Отфильтруйте DataFrame, чтобы отобразить только строки, где значение в определенном столбце превышает заданный порог.

In [ ]:
# 🧩 Ваш код здесь

8. Сгруппируйте DataFrame по одному категориальному столбцу и вычислите среднее значение другого числового столбца для каждой группы, используя `groupby()` и `mean()`.

In [ ]:
# 🧩 Ваш код здесь

9. Создайте массив NumPy 3x3 со случайными числами. Сохраните его в файл в формате `.npy`, используя `np.save()`.

In [ ]:
# 🧩 Ваш код здесь

10. Загрузите массив из файла `.npy`, используя `np.load()`.

In [ ]:
# 🧩 Ваш код здесь

🔥 Отлично! Вы уже освоили половину EASY заданий четвертой недели. Продолжайте в том же духе!

11. Создайте DataFrame Pandas и сохраните его в CSV-файл без индекса, используя `to_csv(index=False)`.

In [ ]:
# 🧩 Ваш код здесь

12. Загрузите DataFrame из CSV-файла, который вы только что сохранили.

In [ ]:
# 🧩 Ваш код здесь

13. Используя NumPy, создайте массив из 100 случайных чисел, представляющих собой имитацию результатов эксперимента. Найдите 95-й перцентиль, используя `np.percentile()`.

In [ ]:
# 🧩 Ваш код здесь

14. В DataFrame с данными о продажах, найдите общую сумму продаж для каждого продукта, используя `groupby()` и `sum()`.

In [ ]:
# 🧩 Ваш код здесь

15. Создайте DataFrame с датами. Отфильтруйте данные за определенный месяц.

In [ ]:
# 🧩 Ваш код здесь

16. Используя NumPy, создайте матрицу идентичности 4x4, используя `np.eye()`.

In [ ]:
# 🧩 Ваш код здесь

17. В DataFrame, замените все вхождения определенного значения в столбце на другое значение, используя `replace()`.

In [ ]:
# 🧩 Ваш код здесь

18. Создайте DataFrame из нескольких Series.

In [ ]:
# 🧩 Ваш код здесь

19. Используя NumPy, создайте массив из 1000 случайных чисел, распределенных по нормальному закону, используя `np.random.normal()`.

In [ ]:
# 🧩 Ваш код здесь

20. В DataFrame, вычислите количество уникальных значений в каждом столбце, используя `nunique()`.

In [ ]:
# 🧩 Ваш код здесь

🎯 Поздравляем! Вы успешно завершили все EASY задания четвертой недели. Вы уже можете эффективно работать с реальными данными!

## ⚙️ MEDIUM Задания

1. Загрузите датасет с информацией о пассажирах Титаника (например, `titanic.csv`). Очистите столбец 'Возраст', заполнив пропущенные значения медианой, и преобразуйте столбец 'Пол' в числовой формат (0/1), используя `fillna()` и `map()`.

Подсказка: если у вас нет файла, создайте тестовый DataFrame с соответствующими столбцами.

In [ ]:
# 🧩 Ваш код здесь

2. Используя NumPy, реализуйте функцию для вычисления матрицы расстояний между всеми парами точек в заданном наборе 2D точек.

In [ ]:
# 🧩 Ваш код здесь

3. Загрузите датасет о ценах на недвижимость. Создайте новый признак 'Цена_за_кв_метр', а затем найдите среднюю цену за квадратный метр для каждого города, используя `groupby()`.

In [ ]:
# 🧩 Ваш код здесь

4. Создайте два DataFrame: один с данными о пользователях (ID, Имя, Страна), другой с данными о покупках (ID_пользователя, Продукт, Сумма). Объедините их, чтобы получить список продуктов, купленных пользователями из определенной страны, используя `merge()` и фильтрацию.

In [ ]:
# 🧩 Ваш код здесь

5. Используя NumPy, создайте функцию для выполнения операции свертки (convolution) одномерного массива с заданным ядром (ядром фильтра).

In [ ]:
# 🧩 Ваш код здесь

💪 Вы отлично справляетесь с более сложными задачами! Продолжайте в том же духе!

6. Загрузите датасет с временными рядами (например, ежедневные продажи). Вычислите ежемесячные агрегированные продажи и визуализируйте их (без использования библиотек для визуализации, только подготовка данных).

In [ ]:
# 🧩 Ваш код здесь

7. Создайте DataFrame с текстовым столбцом, содержащим смешанные данные. Используйте регулярные выражения в Pandas (`.str.extract()`) для извлечения определенных числовых или текстовых паттернов.

In [ ]:
# 🧩 Ваш код здесь

8. Используя NumPy, напишите функцию, которая принимает 2D массив и возвращает его главные компоненты (Principal Components) без использования `sklearn.decomposition.PCA`.

In [ ]:
# 🧩 Ваш код здесь

9. Загрузите датасет с оценками студентов (Имя, Предмет, Оценка). Найдите студентов, у которых средний балл по всем предметам выше 4.5, используя `groupby()`, `mean()`, `filter()`.

In [ ]:
# 🧩 Ваш код здесь

10. Создайте DataFrame с иерархическим индексом (MultiIndex) из двух столбцов. Выполните агрегацию по одному из уровней индекса, используя `level` в `groupby()`.

In [ ]:
# 🧩 Ваш код здесь

🏆 Отлично! Вы успешно справились со всеми заданиями среднего уровня сложности. Теперь вы готовы к настоящим вызовам!

## 🔥 HARD Задания

1. Загрузите большой датасет с логами веб-сервера (timestamp, IP, URL, status_code). Определите топ-10 самых посещаемых URL-адресов, количество уникальных посетителей для каждого URL и среднее время ответа (если доступно), используя `pd.to_datetime()`, `groupby()`, `nunique()`, `mean()`.

In [ ]:
# 🧩 Ваш код здесь

2. Используя NumPy, реализуйте алгоритм сингулярного разложения (Singular Value Decomposition - SVD) для заданной матрицы. Сравните результат с `np.linalg.svd()`.

In [ ]:
# 🧩 Ваш код здесь

3. Загрузите датасет с данными о транзакциях. Разработайте стратегию обнаружения аномалий, основанную на IQR или Z-score, для выявления необычно больших или малых транзакций, используя `quantile()`, `std()`, `mean()`.

In [ ]:
# 🧩 Ваш код здесь

4. Создайте DataFrame с данными о временных рядах (например, ежедневные показания датчиков). Реализуйте функцию для обнаружения пропусков в данных и их интерполяции с использованием различных методов (линейная, полиномиальная) с помощью `interpolate()`.

In [ ]:
# 🧩 Ваш код здесь

5. Используя NumPy, напишите функцию, которая принимает изображение (представленное как 3D массив RGB) и применяет к нему фильтр Гаусса (Gaussian blur) без использования `scipy.ndimage`.

In [ ]:
# 🧩 Ваш код здесь

🔥 Впечатляюще! Вы справились с самыми сложными задачами четвертой недели. Это настоящее достижение!

## 🧠 CONCEPT Задания

1. Объясните концепцию векторизации в NumPy и почему она важна для производительности. Приведите примеры операций, которые выигрывают от векторизации.

✍️ Ваш ответ здесь

2. Опишите процесс работы с пропущенными значениями в реальных датасетах. Какие шаги необходимо предпринять и какие методы Pandas для этого используются?

✍️ Ваш ответ здесь

3. В чем разница между `apply()`, `map()`, и `applymap()` в Pandas? Когда какой метод следует использовать для трансформации данных?

✍️ Ваш ответ здесь

4. Объясните, как эффективно работать с большими датасетами в Pandas, которые не помещаются в оперативную память. Какие стратегии и методы можно использовать?

✍️ Ваш ответ здесь

5. Представьте, что вы разрабатываете ETL-процесс для потоковой обработки данных. Какие методы NumPy/Pandas вы бы использовали для обеспечения высокой производительности и масштабируемости, и какие компромиссы при этом возможны?

✍️ Ваш ответ здесь

🏁 **Поздравляем! Неделя 4 завершена.**

💪 Вы продвинулись на 80% пути к профессиональному уровню.

🧠 Вы освоили работу с реальными датасетами и научились решать практические задачи анализа данных. Эти навыки делают вас готовым к решению реальных бизнес-задач!

# 🧭 НЕДЕЛЯ 5 — Продвинутые методы

### 🎯 Цель недели: Освоение продвинутых методов NumPy и Pandas для решения сложных задач анализа данных.

### 📚 Введение в методы недели

В этой финальной неделе мы рассмотрим продвинутые методы NumPy и Pandas, которые позволят вам решать сложные задачи анализа данных. Эти методы часто используются в реальных проектах и являются мощным инструментом в руках опытного аналитика данных.

#### NumPy:
*   `np.random.default_rng`: Современный генератор случайных чисел.
*   `np.diff`: Вычисление разностей между соседними элементами.
*   `np.histogram`: Построение гистограммы.
*   `np.vectorize`: Векторизация скалярных функций.
*   `np.cov`: Вычисление ковариационной матрицы.
*   `np.linalg.det`: Вычисление определителя матрицы.
*   `np.apply_along_axis`: Применение функции вдоль указанной оси.
*   `np.gradient`: Вычисление градиента.
*   `np.corrcoef`: Вычисление коэффициентов корреляции.
*   `np.einsum`: Эйнштейновская нотация для тензорных операций.

#### Pandas:
*   `pd.read_excel`: Чтение Excel-файлов.
*   `pd.melt`: Преобразование из широкого формата в длинный.
*   `pd.get_dummies`: One-hot кодирование.
*   `pd.cut`: Биннинг данных.
*   `pd.query`: Фильтрация данных с использованием строковых выражений.
*   `pd.crosstab`: Создание таблиц частот.
*   `pd.pivot`: Изменение структуры данных.
*   `pd.resample`: Агрегация временных рядов.
*   `pd.eval`: Вычисление выражений.
*   `pd.to_parquet`, `pd.read_parquet`: Работа с форматом Parquet.
*   `pd.merge_asof`: Асинхронное объединение.
*   `pd.qcut`: Разбиение данных на квантили.

## 💡 EASY Задания

1. Используя `np.random.default_rng`, создайте генератор случайных чисел и сгенерируйте массив целых чисел размером 3x4 в диапазоне от 0 до 100.

In [ ]:
# 🧩 Ваш код здесь

2. Создайте одномерный массив `np.array` и примените `np.diff` для вычисления разностей между соседними элементами.

In [ ]:
# 🧩 Ваш код здесь

3. Создайте массив случайных чисел и используйте `np.histogram` для построения гистограммы с 10 корзинами, вернув только значения гистограммы и границы корзин.

In [ ]:
# 🧩 Ваш код здесь

4. Создайте функцию, которая возводит число в квадрат, затем используйте `np.vectorize` для создания векторизированной версии этой функции и примените ее к массиву чисел.

In [ ]:
# 🧩 Ваш код здесь

5. Сгенерируйте два одномерных массива с помощью `np.random.default_rng` и вычислите их ковариацию с использованием `np.cov`.

In [ ]:
# 🧩 Ваш код здесь

6. Создайте матрицу 3x3 и вычислите ее определитель с помощью `np.linalg.det`.

In [ ]:
# 🧩 Ваш код здесь

7. Используйте `np.apply_along_axis` для вычисления среднего значения по каждой строке двумерного массива.

In [ ]:
# 🧩 Ваш код здесь

8. Создайте одномерный массив и вычислите его градиент с помощью `np.gradient`.

In [ ]:
# 🧩 Ваш код здесь

9. Сгенерируйте два массива случайных данных и вычислите их коэффициент корреляции с помощью `np.corrcoef`.

In [ ]:
# 🧩 Ваш код здесь

10. Используя `pd.read_excel`, загрузите данные из фиктивного Excel-файла (например, `sales.xlsx`) в DataFrame. (Предположите, что файл существует).

Подсказка: если у вас нет файла, создайте тестовый DataFrame и сохраните его в Excel.

In [ ]:
# 🧩 Ваш код здесь

🔥 Отлично! Вы уже освоили половину EASY заданий пятой недели. Продолжайте в том же духе!

11. Создайте DataFrame и используйте `pd.melt` для преобразования его из широкого формата в длинный, выбрав несколько столбцов для плавления.

In [ ]:
# 🧩 Ваш код здесь

12. Загрузите DataFrame и используйте `pd.get_dummies` для выполнения one-hot кодирования категориального столбца.

In [ ]:
# 🧩 Ваш код здесь

13. Создайте Series с числовыми данными и используйте `pd.cut` для биннинга данных на 4 равных интервала.

In [ ]:
# 🧩 Ваш код здесь

14. Создайте DataFrame и используйте `pd.query()` для фильтрации строк по простому условию (например, `столбец > 10`).

In [ ]:
# 🧩 Ваш код здесь

15. Создайте DataFrame с категориальным столбцом и преобразуйте его тип данных в `category` с помощью `.astype('category')`.

In [ ]:
# 🧩 Ваш код здесь

16. Используя `pd.crosstab`, создайте таблицу частот для двух категориальных столбцов в DataFrame.

In [ ]:
# 🧩 Ваш код здесь

17. Загрузите DataFrame и используйте `pd.pivot` для изменения его структуры, сделав уникальные значения одного столбца новыми столбцами.

In [ ]:
# 🧩 Ваш код здесь

18. Создайте DataFrame с временными метками и используйте `pd.resample` для агрегации данных по месяцам, вычисляя среднее значение.

In [ ]:
# 🧩 Ваш код здесь

19. Создайте DataFrame и используйте `pd.eval()` для выполнения простой арифметической операции между двумя столбцами (например, `столбец1 + столбец2`).

In [ ]:
# 🧩 Ваш код здесь

20. Сохраните небольшой DataFrame в формат Parquet с помощью `pd.to_parquet` и затем прочитайте его обратно с помощью `pd.read_parquet`.

In [ ]:
# 🧩 Ваш код здесь

🎯 Поздравляем! Вы успешно завершили все EASY задания пятой недели. Вы уже можете использовать продвинутые методы NumPy и Pandas!

## ⚙️ MEDIUM Задания

1. Используя `np.einsum`, вычислите сумму произведений двух матриц (матричное умножение). Проверьте результат с помощью `np.dot`.

In [ ]:
# 🧩 Ваш код здесь

2. Создайте функцию, которая нормализует одномерный массив (приводит значения к диапазону [0, 1]), затем используйте `np.apply_along_axis` для применения этой функции к каждой колонке двумерного массива.

In [ ]:
# 🧩 Ваш код здесь

3. Сгенерируйте данные для 1000 студентов: `id`, `факультет` (3-4 категории), `баллы_математика`, `баллы_физика`. Используйте `pd.pivot_table` для создания сводной таблицы, показывающей средние баллы по предметам для каждого факультета.

In [ ]:
# 🧩 Ваш код здесь

4. Используя `np.random.multivariate_normal`, сгенерируйте 500 двумерных точек, представляющих данные с определенной средней и ковариационной матрицей. Визуализируйте эти точки (без кода визуализации, только генерация данных).

In [ ]:
# 🧩 Ваш код здесь

5. Загрузите DataFrame с данными о транзакциях, содержащими `timestamp` и `amount`. Используйте `pd.resample` с `pd.Grouper` для агрегации данных по неделям и вычисления суммы `amount` и среднего `amount`.

In [ ]:
# 🧩 Ваш код здесь

💪 Вы отлично справляетесь с более сложными задачами! Продолжайте в том же духе!

6. Создайте DataFrame с пропущенными значениями. Используйте `pd.eval()` для создания нового столбца, который является результатом сложной арифметической операции, игнорируя NaN, а затем заполните NaN в исходном DataFrame методом `ffill`.

In [ ]:
# 🧩 Ваш код здесь

7. Используя `pd.merge_asof`, объедините два DataFrame: один с данными о ценах акций (`timestamp`, `price`) и другой с данными о новостях (`timestamp`, `headline`), чтобы привязать каждую цену к ближайшей предыдущей новости.

In [ ]:
# 🧩 Ваш код здесь

8. Создайте DataFrame с числовыми данными. Используйте `pd.qcut` для разбиения данных на 5 квантилей и создайте новый столбец с метками квантилей.

In [ ]:
# 🧩 Ваш код здесь

9. Реализуйте функцию для вычисления обратной матрицы 3x3 с помощью `np.linalg.inv`. Проверьте, что произведение исходной матрицы на обратную дает единичную матрицу.

In [ ]:
# 🧩 Ваш код здесь

10. Загрузите большой DataFrame. Используйте `astype('category')` для оптимизации использования памяти для одного или нескольких категориальных столбцов. Сравните потребление памяти до и после оптимизации (без кода сравнения, только описание действия).

In [ ]:
# 🧩 Ваш код здесь

🏆 Отлично! Вы успешно справились со всеми заданиями среднего уровня сложности. Теперь вы готовы к настоящим вызовам!

## 🔥 HARD Задания

1. Используя `np.einsum`, реализуйте вычисление сингулярного разложения (SVD) для матрицы 4x4. Сравните производительность с `np.linalg.svd` для больших матриц (без кода сравнения, только описание задачи).

In [ ]:
# 🧩 Ваш код здесь

2. Создайте DataFrame с историческими данными о ценах акций (например, `timestamp`, `open`, `high`, `low`, `close`, `volume`). Используя `pd.resample` и `pd.Grouper`, рассчитайте скользящее среднее (rolling mean) цены закрытия за 30 дней и экспоненциальное скользящее среднее (expanding mean) за весь период для каждого года.

In [ ]:
# 🧩 Ваш код здесь

3. Сгенерируйте данные для симуляции Монте-Карло: 100000 случайных выборок из многомерного нормального распределения (`np.random.multivariate_normal`). Затем, используя `np.apply_along_axis` или `np.vectorize`, рассчитайте для каждой выборки некоторую сложную функцию (например, сумму квадратов элементов, деленную на их произведение).

In [ ]:
# 🧩 Ваш код здесь

4. Используя `pd.merge_ordered` и `pd.merge_asof`, объедините три DataFrame: данные о заказах (`order_id`, `timestamp`, `customer_id`), данные о платежах (`payment_id`, `timestamp`, `order_id`, `amount`) и данные о курсах валют (`currency`, `timestamp`, `rate`). Цель — получить полную картину заказа с учетом курса валют на момент ближайшего платежа и всех последующих платежей.

In [ ]:
# 🧩 Ваш код здесь

5. Разработайте систему для анализа временных рядов, используя `np.gradient` для определения точек изменения тренда и `np.diff` для вычисления скорости изменения. Примените это к DataFrame с данными о температуре за год, чтобы найти дни с наиболее резкими изменениями температуры.

In [ ]:
# 🧩 Ваш код здесь

🔥 Впечатляюще! Вы справились с самыми сложными задачами пятой недели. Это настоящее достижение!

## 🧠 CONCEPT Задания

1. Объясните, в чем заключается преимущество `np.einsum` перед традиционными операциями NumPy (например, `np.dot`, `transpose`, `sum`) для сложных тензорных операций. Приведите примеры, когда `einsum` значительно упрощает код.

✍️ Ваш ответ здесь

2. Опишите сценарии использования `np.vectorize` и `np.apply_along_axis`. В каких случаях каждый из них предпочтительнее, и какие у них ограничения по сравнению с полностью векторизованными операциями NumPy?

✍️ Ваш ответ здесь

3. Сравните `pd.pivot`, `pd.pivot_table` и `pd.crosstab`. Объясните их основные различия, области применения и когда следует выбирать каждый из них для агрегации и изменения формы данных.

✍️ Ваш ответ здесь

4. Подробно объясните разницу между `pd.merge_asof` и `pd.merge_ordered`. Приведите примеры реальных бизнес-задач, где каждый из этих методов является оптимальным решением.

✍️ Ваш ответ здесь

5. Обсудите важность и практическое применение оптимизации памяти с использованием типа данных `category` в Pandas и sparse data. В каких случаях эти методы наиболее эффективны и какие потенциальные недостатки они имеют?

✍️ Ваш ответ здесь

🏁 **Поздравляем! Неделя 5 завершена.**

💪 Вы продвинулись на 100% пути к профессиональному уровню.

🧠 Вы освоили продвинутые методы NumPy и Pandas, которые позволят вам решать сложные задачи анализа данных. Эти навыки делают вас настоящим профессионалом в области анализа данных!

# 🎓 Capstone Projects (объединение NumPy + Pandas)

Пришло время применить все полученные знания на практике! Ниже представлены три проекта, которые помогут вам закрепить навыки работы с NumPy и Pandas в реальных сценариях.

## 🛒 Проект 1: Анализ данных о продажах

*   Загрузите несколько CSV-файлов с данными о продажах за разные месяцы.
*   Объедините их в один DataFrame.
*   Очистите данные: обработайте пропущенные значения, удалите дубликаты.
*   Создайте новые признаки: месяц, день недели, общая стоимость заказа.
*   Сгруппируйте данные по продуктам и найдите топ-5 самых продаваемых товаров.
*   Визуализируйте результаты (подготовьте данные для визуализации).


In [ ]:
# 🧩 Ваш код здесь


## 📝 Проект 2: Анализ текстовых данных

*   Загрузите датасет с отзывами на фильмы.
*   Очистите текстовые данные: приведите к нижнему регистру, удалите знаки препинания и стоп-слова.
*   Создайте новый признак: длина отзыва.
*   Проведите сентимент-анализ (без использования готовых библиотек, на основе словаря тональности).
*   Сгруппируйте данные по фильмам и найдите фильмы с самым высоким и самым низким средним рейтингом.


In [ ]:
# 🧩 Ваш код здесь


## 💹 Проект 3: Финансовый анализ

*   Загрузите исторические данные о ценах на акции нескольких компаний.
*   Рассчитайте дневную доходность для каждой акции.
*   Вычислите скользящее среднее и стандартное отклонение доходности.
*   Найдите корреляцию между доходностями разных акций.
*   Реализуйте простую торговую стратегию и оцените ее прибыльность.


In [ ]:
# 🧩 Ваш код здесь


# 🏆 Поздравляем с завершением курса, NotHero!

## 🚀 Вы прошли весь путь от основ до продвинутых методов NumPy и Pandas!

### 💪 Ваши достижения:
- Освоили основы работы с массивами NumPy и таблицами Pandas
- Научились индексировать, агрегировать и объединять данные
- Овладели методами обработки, очистки и статистического анализа
- Применили знания на практике, работая с реальными датасетами
- Изучили продвинутые методы для решения сложных задач анализа данных

### 🧠 Приобретенные навыки:
- **Манипуляция данными**: преобразование, фильтрация, агрегация
- **Очистка данных**: обработка пропущенных значений, дубликатов, выбросов
- **Статистический анализ**: вычисление статистик, корреляций, распределений
- **Оптимизация**: эффективная работа с большими объемами данных
- **Продвинутые методы**: тензорные операции, сложные объединения, временные ряды

### 🔮 Что дальше?
Теперь вы полностью готовы к следующему этапу — **Машинному обучению**! Вы сможете:
- Эффективно подготавливать данные для моделей ML
- Создавать признаки и трансформировать данные
- Анализировать результаты моделей
- Работать с большими датасетами

### 📈 Ваш путь к успеху:
«Мастерство в анализе данных — это не конечная точка, а непрерывный путь. Каждый день приносит новые вызовы и возможности для роста. Продолжайте учиться, экспериментировать и применять свои знания на практике!»

## 🎉 Удачи в вашем дальнейшем пути в мире данных и искусственного интеллекта!
